controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# API Authenticator
api_auth:
    path: /api/auth

# Handle Module Router
module_controllers:
    resource: "@Module/config/routes.yaml"
